name: Build & Release

on:
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install NSIS (Windows only)
        if: matrix.os == 'windows-latest'
        run: choco install nsis

      - name: Install Dependencies
        run: npm ci

      - name: Build Application (Windows)
        if: matrix.os == 'windows-latest'
        run: npm run make -- --platform=win32

      - name: Build Application (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: npm run make -- --platform=linux

      - name: Build Application (MacOS)
        if: matrix.os == 'macos-latest'
        run: npm run make -- --platform=darwin

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: out/make
