name: Publish on push to main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Build App
        run: npm run make

      - name: Get Current Date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> "$GITHUB_OUTPUT"

      - name: Release build
        uses: softprops/action-gh-release@v2
        with:
          files: out/make/*
          name: ${{env.RELEASE_NAME}}
          generate_release_notes: true
          prerelease: true
          draft: true
        env:
          RELEASE_NAME: nightly-${{steps.date.outputs.date}}